# Тема “Вычисления с помощью Numpy”

### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 3, 1], [6,8, 11, 10, 7]])

In [3]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
a.shape

(2, 5)

In [5]:
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [7]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [8]:
a0 = a_centered[:, 0]
a0

array([-1.,  0.,  1.,  1., -1.])

In [9]:
a1 = a_centered[:, 1]
a1

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [10]:
a_centered_sp = a0 @ a1
a_centered_sp

8.0

In [11]:
N = a.shape[0]
N

5

In [12]:
a_centered_sp / (N - 1)

2.0

Задание 4

In [13]:
my_cov = np.cov(a.transpose())
my_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [14]:
my_cov[0, 1]

2.0

# Тема “Работа с данными в Pandas”

### Задание 1

In [15]:
import pandas as pd

In [16]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                      columns = ['author_id', 'author_name'])

In [17]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [18]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]}, 
                   columns = ['author_id', 'book_title', 'price'])

In [19]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [20]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'left')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [21]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [22]:
authors_price_max = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns = {'price': 'max price'})
authors_price_max

max price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [23]:
authors_price_min = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns = {'price': 'min price'})
authors_price_min

min price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [24]:
authors_price_mean = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns = {'price': 'mean price'}).round()
authors_price_mean

mean price
author_name            
Островский        330.0
Тургенев          367.0
Чехов             475.0

In [25]:
authors_stat = pd.concat([authors_price_max, authors_price_min, authors_price_mean], axis = 1)
authors_stat

max price  min price  mean price
author_name                                  
Островский         370        290       330.0
Тургенев           450        300       367.0
Чехов              500        450       475.0

### Задание 5

In [26]:
cover = pd.DataFrame({'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
'cover':['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns = ['book_title', 'cover'])

In [27]:
cover

book_title    cover
0           Отцы и дети  твердая
1                 Рудин   мягкая
2     Дворянское гнездо   мягкая
3      Толстый и тонкий  твердая
4       Дама с собачкой  твердая
5                 Гроза   мягкая
6  Таланты и поклонники   мягкая

In [28]:
authors_price = pd.merge(authors_price, cover, on = 'book_title', how = 'inner')

In [29]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [31]:
?pd.pivot_table